### ISSUE TITLE
MathtextBackendPdf class Deprecated

### ISSUE THREAD

**Issue by tbpassin** [rst2pdf/rst2pdf#1033]
Not a current problem, but in converting an RsT file to pdf I noted the following message from Matplotlib:

```
The MathtextBackendPdf class was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use MathtextBackendPath instead.
```

It's used by _math_flowable.py_.

I added this issue in case the deprecation hasn't been noticed as yet.

**Comment by akrabat** [comment]
> I added this issue in case the deprecation hasn't been noticed as yet.

I think you could safely assume this! :)

**Comment by akrabat** [comment]
Fixed not @tbpassin! If you have a moment to check out https://github.com/rst2pdf/rst2pdf/pull/1047 and see if it breaks your usage, I'd appreciate it.

**Comment by tbpassin** [comment]
#1047 does produce better output, but it's still not without problems.  I have attached 1) output with old version; 2) output with 1047 version; 3) the input rst file (with added extension of ".txt" so that github will accept it); 4) the desired rendering as rendered by docutils to html (I realize that the new left justification is not handled yet by my rst file) - please ignore the solarized theme colors since I don't expect them to be in the pdf output!).  Here is a transcript of my console session that generated the pdf output:

```
C:\test\leo\sphinx-test\doc>set PYTHONPATH=C:\test\rst2pdf\rst2pdf-1033-replace-mathtextbackendpdf

C:\test\leo\sphinx-test\doc>rst2pdf Formula.rst
[ERROR] math_flowable.py:60 Math error in wrap:
$\alpha_t(i) &=P(O_1,O_2,…O_t,q_t)=S_iλ\\
^
Expected end of text, found '$'  (at char 0), (line:1, col:1)
[ERROR] math_flowable.py:102 Math error:
$\alpha_t(i) &=P(O_1,O_2,…O_t,q_t)=S_iλ\\
^
Expected end of text, found '$'  (at char 0), (line:1, col:1)
```
I think that the aligned equation block at the end is asking too much because Matplotlib can only render a line at a time, if I understand correctly.

[Formula-old.pdf](https://github.com/rst2pdf/rst2pdf/files/7722270/Formula-old.pdf)
[Formula_new.pdf](https://github.com/rst2pdf/rst2pdf/files/7722271/Formula_new.pdf)
[Formula.rst.txt](https://github.com/rst2pdf/rst2pdf/files/7722277/Formula.rst.txt)
![Formula_rst_desired_rendering](https://user-images.githubusercontent.com/36974235/146256281-77ee4c71-86a0-484c-a356-666c711733fc.png)

**Comment by akrabat** [comment]
Thanks!

**Comment by akrabat** [comment]
Looking at it, the new pdf is better than the old in that the inline formulae are now visible and now below the line. I don't see any regressions, but the "Formula (2)" equation remain very broken.

This is good to know. I'll see what can be done about the last formula.

**Comment by tbpassin** [comment]
The new is definitely better than the old.  One of the things that still remains is that the several lines of equations do not quite have satisfactory line spacing - they look irregular.  That looks about the same as from before the changes.  As for the "Formula two" equations, they are supposed to be an aligned block, but I don't think that Matplotlib understands the Latex for that, so we are probably not going to do too much better there.

Oh, and I said that the HTML screen shot had been rendered by docutils.  Of course, the actual rendering of the math was done by MathJax.

The error messages on the console didn't prevent the pdf file from getting generated, but trying to build the same thing using Sphinx, there was no output, so apparently those error messages did prevent Sphinx from completing.

Thanks for your efforts to update the math rendering!

**Comment by akrabat** [comment]
For the newlines, should rst2pdf exit with an error message saying that it doesn't support new lines in the math directive?

**Comment by akrabat** [comment]
@tbpassin I have updated the spacing. Does it now work better in your case?

Multi-line is much more of a  challenge and it doesn't look like I can solve that this time around.

**Comment by tbpassin** [comment]
An error message about not supporting multi-line in math directives sounds right ot me.

**Comment by tbpassin** [comment]
I've tried the new version and yes, the spacing is much better.  I would say it's acceptable, and a big improvement.

Now that we're getting down to nits, I notice that the inline math font size seems a little larger than the block size.  If they could be the same size, that would be more pleasant to read.  I realize that would probably be hard since (IIUC) for the inline expressions you are generating an svg image and inserting it into the line.  Making the display size a bit smaller would also make the inline image appear a bit sharper - there is a small but noticeable difference in sharpness between the inline and the block renderings.  But maybe that's not possible with SVG.  I know that the few times I've fooled around with fractional font sizes in SVG, I didn't have a lot of choice.

There are still the output error messages I mentioned earlier.  They didn't prevent rst2pdf from creating the pdf file, but they did apparently prevent Sphinx from generating its pdf output file.

```c:\test\leo\sphinx-test\doc>rst2pdf Formula.rst
[ERROR] math_flowable.py:65 Math error in wrap:
$\alpha_t(i) &=P(O_1,O_2,…O_t,q_t)=S_iλ\\
^
Expected end of text, found '$'  (at char 0), (line:1, col:1)
[ERROR] math_flowable.py:107 Math error:
$\alpha_t(i) &=P(O_1,O_2,…O_t,q_t)=S_iλ\\
^
Expected end of text, found '$'  (at char 0), (line:1, col:1)
[ERROR] math_flowable.py:108 Math error!
Traceback (most recent call last):
  File "C:\Users\tom\AppData\Roaming\Python\Python39\site-packages\matplotlib\_mathtext.py", line 2237, in parse
    result = self._expression.parseString(s)
  File "c:\program files\python39\lib\site-packages\pyparsing.py", line 1955, in parseString
    raise exc
  File "c:\program files\python39\lib\site-packages\pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text, found '$'  (at char 0), (line:1, col:1)
```

**Comment by akrabat** [comment]
> There are still the output error messages I mentioned earlier. They didn't prevent rst2pdf from creating the pdf file, but they did apparently prevent Sphinx from generating its pdf output file.

I wonder why? Our test, `sphinx-issue252`, does generate a pdf, though it's wrong for multi-line as you can see [here](https://github.com/rst2pdf/rst2pdf/blob/92773770fc698ff7fb6fa3d98be6fecdc6e2ea26/rst2pdf/tests/reference/sphinx-issue252.pdf).

**Comment by akrabat** [comment]
> Now that we're getting down to nits, I notice that the inline math font size seems a little larger than the block size. If they could be the same size, that would be more pleasant to read. I realize that would probably be hard since (IIUC) for the inline expressions you are generating an svg image and inserting it into the line. Making the display size a bit smaller would also make the inline image appear a bit sharper - there is a small but noticeable difference in sharpness between the inline and the block renderings. But maybe that's not possible with SVG. I know that the few times I've fooled around with fractional font sizes in SVG, I didn't have a lot of choice.

It's actually PNG, but the sentiment holds.

However, it turns out that using `mathtext.math_to_image` isn't as good as rendering with PIL where we can use a scaling factor to get a better quality image. 

It's still not as good as math directive (particularly for multi-line equations), but let me know if it's better for you too.

**Comment by tbpassin** [comment]
For using Sphinx, I run it with a little Python script with all the Sphinx parameters in the command line (for reasons that don't matter here).  Here is the Python script I'm using:

```
import sys
from subprocess import Popen

pyexe = sys.executable

cmd = [pyexe, '-m', 'sphinx', '-C',
        '-D', 'master_doc=index',
        '-D', 'source_suffix=.rst',
        '-D', 'project=Sphinx Test',
        '-D', 'extensions=rst2pdf.pdfbuilder',
        '-D', "pygments_style = 'sphinx'",
        '-b', 'pdf',
        '.', r'result\pdf']

Popen(cmd)
```

This script runs Sphinx and also emits the same error message I get using rst2pdf directly.  However, the .pdf file that Sphinx creates for me contains 0 bytes.

Note that the full document includes several .rst files, not just the one with the math.  However, it's only the one with the math that emits errors.  A nearly identical script succeeds in producing HTML output.  This makes me think that I have got all the right -D directives in place.  But any suggestions gratefully received!

I didn't include the entire error message last time.  There was a second part:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\test\rst2pdf\rst2pdf-1033-replace-mathtextbackendpdf\rst2pdf\math_flowable.py", line 86, in drawOn
    (width, height, descent, glyphs, rects,) = self.parser.parse(
  File "C:\Users\tom\AppData\Roaming\Python\Python39\site-packages\matplotlib\mathtext.py", line 435, in parse
    return self._parse_cached(s, dpi, prop, _force_standard_ps_fonts)
  File "C:\Users\tom\AppData\Roaming\Python\Python39\site-packages\matplotlib\mathtext.py", line 456, in _parse_cached
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "C:\Users\tom\AppData\Roaming\Python\Python39\site-packages\matplotlib\_mathtext.py", line 2239, in parse
    raise ValueError("\n".join(["",
ValueError:
$\alpha_t(i) &=P(O_1,O_2,…O_t,q_t)=S_iλ\\
^
Expected end of text, found '$'  (at char 0), (line:1, col:1)
[ERROR] createpdf.py:1119 Template 'twoColumn' is not defined

handle_pageBegin args=() 1
```

**Comment by akrabat** [comment]
@tbpassin `twoColumn` isn't part of the default styles any more. You need to add the `twocolumn` style. 

For stock rst2pdf, you'd use `-s twocolumn` and for sphinx, I think it's `pdf_stylesheets = ['twocolumn']`

**Comment by tbpassin** [comment]
Yes, that did the trick.  I added 
```
'-D', 'pdf_stylesheets=twocolumn'
```
to the argument list, and now I get the Sphinx output. Thanks!

**Comment by tbpassin** [comment]
Yes, this way reads well.  As for multiline equation blocks with possible alignment and equation numbers, I know that is seriously complicated and would be a lot to work up.  

> It's still not as good as math directive (particularly for multi-line equations), but let me know if it's better for you too.

**Comment by akrabat** [comment]
Thanks. I think we'll call this done then. I've created #1051 to track the multi-line support.

**Comment by tbpassin** [comment]
Thanks for your work on this!
