### ISSUE TITLE
Build warnings triggered when run using Sphinx 2.2

### ISSUE THREAD

**Issue by johnthagen** [rst2pdf/rst2pdf#801]
**Description of problem**

Several warnings are triggered when building PDF output the latest master branch using Sphinx 2.2 and Python 3.7.

```
$ sphinx-build -a -n -W -b pdf . _build
...
.tox/docs/lib/python3.7/importlib/__init__.py:127: RemovedInSphinx30Warning: sphinx.environment.NoUri is deprecated. Check CHANGES for Sphinx API modifications.
  return _bootstrap._gcd_import(name[level:], package, level)

.tox/docs/lib/python3.7/site-packages/rst2pdf/rson.py:140: FutureWarning: Possible nested set at position 2
  splitter = re.compile(pattern).split

.tox/docs/lib/python3.7/site-packages/rst2pdf/pdfbuilder.py:602: RemovedInSphinx30Warning: sphinx.util.osutil.ustrtime is deprecated for removal
  date=ustrftime(self.config.today_fmt or _('%B %d, %Y'))
```

At least the bottom two are generated from this package, the first one I'm not sure on.

🖥 **Versions**

Python 3.7

Sphinx 2.2.0

rst2pdf master branch https://github.com/rst2pdf/rst2pdf/commit/25713408cbe8da5be0f12f1176b11fddd1d95774

`sphinx-rtd-theme==0.4.3`

**Comment by johnthagen** [comment]
See #778

**Comment by akrabat** [comment]
Thanks for the report. Out of interest, have you just started to use rst2pdf and how did you hear about it?

**Comment by johnthagen** [comment]
> have you just started to use rst2pdf

I have just started using `rst2pdf`, yes. 

> how did you hear about it

I believe I googled "Create PDF using Sphinx" and found this SO post: https://stackoverflow.com/questions/39534718/how-to-create-a-pdf-out-of-sphinx-documentation-tool/47720278#47720278

So far it's been great! All we need is probably some doc updates (#802) and to get a new release on PyPI. [Given Python 2 is EOL in just a couple months](https://pythonclock.org/), all of our projects are Python 3-only so we have to point to the `master` branch on GitHub in our requirements.

**Comment by akrabat** [comment]
Thanks @johnthagen. I think #785 is the only blocker for a PyPI release with Python 3 support.

**Comment by akrabat** [comment]
I believe that this is fixed as #788 is now merged.

**Comment by johnthagen** [comment]
@akrabat Can confirm the warnings are now gone as of the latest master.

**Comment by johnthagen** [comment]
@akrabat We are still getting these warning using `rst2pdf==0.96`:

```
/.tox/docs/lib/python3.7/site-packages/rst2pdf/rson.py:140: FutureWarning: Possible nested set at position 2
  splitter = re.compile(pattern).split
```

I think one of the warnings still needs to be fixed.

**Comment by davelawr** [comment]
Hi, still getting this on 0.96.dev0 running on Ubuntu focal:

`/usr/lib/python3/dist-packages/rst2pdf/rson.py:140: FutureWarning: Possible nested set at position 2
splitter = re.compile(pattern).split
`

**Comment by samuelharmer** [comment]
Windows with Miniconda installed Python, pip installed rst2pdf. Doesn't happen with all my input files though so assume there is a particular problem with some of them. Let me know if I can help identify the cause, or whether this wants its own bug report?

```
${HOME}\.conda\envs\general\lib\site-packages\rst2pdf\rson.py:119: FutureWarning: Possible nested set at position 2
  splitter = re.compile(pattern).split

python --version
Python 3.8.5
rst2pdf --version
0.98
```

OK, I was going to attempt to provide a code sample but this is especially strange. Given the exact same input, it doesn't happen every single time.

**Comment by akrabat** [comment]
@samuelharmer This has been fixed in #880 and will be in the next release. It is harmless on Python 3.8 as it's a warning for a change to Python expected in the future.

**Comment by samuelharmer** [comment]
@akrabat thanks for the pointer, #880 didn't come up in my Google for the error message so hopefully this will help anyone else too 😄
